apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app: stride
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stride
  template:
    metadata:
      labels:
        app: stride
    spec:
      containers:
      - name: my-application
        image: stride:latest
        ports:
        - containerPort: 80
